export const ApiEndPoints = {

  //   REGISTRATION API
  REGISTRATION_API: "REGISTRATION_API",

  // LOGIN API
  LOGIN_API: '/login',

  // FORGET PASSWORD
  FORGET_PASSWORD_API: "FORGETPASSWORDAPI",

}