// this my action type file
// Login Types
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
// export const LOGOUT = "LOGOUT";

// Register Types
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// Tutors Register Types
export const TUTORSREGISTER_SUCCESS = "TUTORSREGISTER_SUCCESS";
export const TUTORSREGISTER_FAILURE = "TUTORSREGISTER_FAILURE";

// Token Types
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const REMOVE_AUTH_TOKEN = "REMOVE_AUTH_TOKEN";

// Latest Types
export const FETCH_LATEST_SUCCESS = "FETCH_LATEST_SUCCESS";
export const FETCH_LATEST_FAILURE = "FETCH_LATEST_FAILURE";

// TUTORS SHOW Types
export const TUTORS_SHOW_SUCCESS = "TUTORS_SHOW_SUCCESS";
export const TUTORS_SHOW_FAILURE = "TUTORS_SHOW_FAILURE";

// SPECIALTIES SHOW Types
export const SPECIALTIESSHOW_SUCCESS = "SPECIALTIESSHOW_SUCCESS";
export const SPECIALTIESSHOW_FAILURE = "SPECIALTIESSHOW_FAILURE";

// SPEAK SHOW Types
export const SPEAK_SHOW_SUCCESS = "SPEAK_SHOW_SUCCESS";
export const SPEAK_SHOW_FAILURE = "SPEAK_SHOW_FAILURE";

//COUNTRY_SHOW Type
export const COUNTRY_SHOW_SUCCESS = "COUNTRY_SHOW_SUCCESS";
export const COUNTRY_SHOW_FAILURE = "COUNTRY_SHOW_FAILURE";

//RATING_SHOW Type
export const RATING_SHOW_SUCCESS = "RATING_SHOW_SUCCESS";
export const RATING_SHOW_FAILURE = "RATING_SHOW_FAILURE";

//CREATETUTOR_CATEGORIES Type
export const CREATETUTOR_CATEGORIES_SUCCESS = "CREATETUTOR_CATEGORIES_SUCCESS";
export const CREATETUTOR_CATEGORIES_FAILURE = "CREATETUTOR_CATEGORIES_FAILURE";

//CREATE_SPEAKER Type
export const CREATE_SPEAKER_SUCCESS = "CREATE_SPEAKER_SUCCESS";
export const CREATE_SPEAKER_FAILURE = "CREATE_SPEAKER_FAILURE";

//BLOG SHOW
export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_FAILURE = "BLOG_FAILURE";

//BLOG DETAILS SHOW
export const BLOGDETAILS_SUCCESS = "BLOGDETAILS_SUCCESS";
export const BLOGDETAILS_FAILURE = "BLOGDETAILS_FAILURE";

// Slot Show
export const FETCH_SLOTS_SUCCESS = "FETCH_SLOTS_SUCCESS";
export const FETCH_SLOTS_FAILURE = "FETCH_SLOTS_FAILURE";

// Slot Show
export const FETCH_LEVEL_SUCCESS = "FETCH_LEVEL_SUCCESS";
export const FETCH_LEVEL_FAILURE = "FETCH_LEVEL_FAILURE";

// Slot Show
export const FETCH_CERTIFICATION_SUCCESS = "FETCH_CERTIFICATION_SUCCESS";
export const FETCH_CERTIFICATION_FAILURE = "FETCH_CERTIFICATION_FAILURE";

// tutors Show count
export const FETCH_TUTORCOUNT_SUCCESS = "FETCH_TUTORCOUNT_SUCCESS";
export const FETCH_TUTORCOUNT_FAILURE = "FETCH_TUTORCOUNT_FAILURE";
